// src/steps/gptReply.ts

import { OpenAI } from "openai";
import { ParsedEntry } from "../utils/types";
import { logStep } from "./stepLogger";
import dotenv from "dotenv";

dotenv.config();

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY, //set in .env
});

export async function generateReply(parsed: ParsedEntry): Promise<string> {
  const prompt = `You are an empathetic assistant. Generate one short response (≤55 characters) mirroring the entry’s vibe and theme.

Parsed Entry:
${JSON.stringify(parsed, null, 2)}

Reply ONLY with the text:`;

  const response = await openai.chat.completions.create({
    model: "gpt-4o-mini", // or "gpt-3.5-turbo" if needed
    messages: [
      { role: "system", content: "You are a highly empathetic assistant. You reply with care." },
      { role: "user", content: prompt },
    ],
    temperature: 0.7,
    max_tokens: 200, // to keep it concise
  });

  const reply = response.choices?.[0]?.message?.content?.trim() ?? "[fallback reply]";

  logStep("GPT_REPLY", parsed, reply, "Generated by OpenAI GPT");
  return reply;
}
